
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:59 (PROJECT)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
